### ISSUE TITLE
help!!!

### ISSUE THREAD

**Issue by Ggmatch** [czczup/UrbanRegionFunctionClassification#2]
大佬，能问下train.py文件中read_and_decode_train函数里为啥要对读入的训练图像进行裁剪、翻转等操作？另外，扩充到8万多张图片，也没有图片扩充代码吗？

**Comment by czczup** [comment]
随机裁剪和翻转是为了数据增强，扩充图片是随机过采样，check_data.ipynb里有代码。

**Comment by Ggmatch** [comment]
谢谢大佬的答疑。只不过我听说过上菜样与下采样，之前没接触过过采样😐


 
---Original---

**Comment by lhqcfk20170112** [comment]
大佬,运行tfrecords.py时显示AttributeError: 'NoneType' object has no attribute 'tobytes'
是什么问题

**Comment by czczup** [comment]
> 大佬,运行tfrecords.py时显示AttributeError: 'NoneType' object has no attribute 'tobytes'
> 是什么问题

我估计你文件的位置和我不一样

**Comment by lhqcfk20170112** [comment]
文件位置没有错啊,你当初出现这种问题没有呢?大佬感觉问题出在那个地方

**Comment by Ggmatch** [comment]
> 文件位置没有错啊,你当初出现这种问题没有呢?大佬感觉问题出在那个地方

我没有出错

**Comment by lhqcfk20170112** [comment]
谢谢,我查了很多也没有发现是什么原因

**Comment by czczup** [comment]
> 谢谢,我查了很多也没有发现是什么原因

你是运行中途出的错还是一开始就出错呀？报这个错是因为opencv加载图像失败了。

**Comment by lhqcfk20170112** [comment]
运行这个没有问题visit2array.py,运行python tfrecord.py的时候直接出错

**Comment by Ggmatch** [comment]
> 运行这个没有问题visit2array.py,运行python tfrecord.py的时候直接出错

**Comment by Ggmatch** [comment]
> 运行这个没有问题visit2array.py,运行python tfrecord.py的时候直接出错

tfrecord.py文件我没有运行，我是自己写了一个tfrecord.py文件，因为之前我没有找到扩充图片的代码

**Comment by Ggmatch** [comment]
> 运行这个没有问题visit2array.py,运行python tfrecord.py的时候直接出错

tfrecord.py文件最大的错误应该在要有扩充的图片样本，会发生越界错误，也就是读入了一个NULL图片

**Comment by Ggmatch** [comment]
> 运行这个没有问题visit2array.py,运行python tfrecord.py的时候直接出错



> 运行这个没有问题visit2array.py,运行python tfrecord.py的时候直接出错

**Comment by lhqcfk20170112** [comment]
那我应该在公开的tfrecord.py上面如何操作呢?

**Comment by Ggmatch** [comment]
> 运行这个没有问题visit2array.py,运行python tfrecord.py的时候直接出错



> 那我应该在公开的tfrecord.py上面如何操作呢?



> 那我应该在公开的tfrecord.py上面如何操作呢?
用大佬的代码的话，就先利用扩充代码check_data.ipynb扩充图片数据集，再运行tfrecord.py文件，就不会有错

**Comment by lhqcfk20170112** [comment]
公开的数据文件夹里面有扩充的啊,

**Comment by Ggmatch** [comment]
> 公开的数据文件夹里面有扩充的啊,
公开的数据文件夹中只有oversamples.txt扩充完后图片存储的路径，那些扩充的图片没有啊

**Comment by lhqcfk20170112** [comment]
好的,谢谢大佬
